language: node_js
node_js:
  - v12.19.0
env:
  - PORT=5000
services:
  - mongodb
script:
  - npm ci
  - npm test:coveralls
  - npm run cover
  deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
  branch: master
 notifications:
   email: false
after_success:
  - npm run coveralls