--- 
after_success: 
  - "npm run coveralls"
env: 
  - PORT=4000
language: node_js
node_js: 
  - stable
notifications: 
  email: false
script: 
  - "npm ci"
  - "npm run test"
  - "npm run coverage"
services: 
  - mongodb
