after_success: 
  - "test $TRAVIS_PULL_REQUEST = false && git push"
branches: 
  only: 
    - master
    - /^deploy-.*$/
env: 
  - PORT=4000
language: node_js
node_js: 
  - "0.10"
  - stable
services: 
  - mongodb