after_success: 
  - "test $TRAVIS_PULL_REQUEST = false && git push"
before_script: 
  - "bower install"
branches: 
  only: 
    - master
    - /^deploy-.*$/
env: 
  global: 
    - PORT=5000
language: node_js
node_js: 
  - "0.10"
  - stable
services: 
  - mongodb