after_success: 
  - "test $TRAVIS_PULL_REQUEST = false && git push"
branches: 
  only: 
    - master
    - /^deploy-.*$/
env: 
  - PORT=4000
language: node_js
node_js: 
  - "12.19.0"
  - stable
script: 
  - "npm run test"
  - "npm run coveralls"
  - "npm run cover"
services: 
  - mongodb